title: I Am Will Thomason
author: Will Thomason
email: will@asteponline.org
description: > # this means to ignore newlines until "baseurl:"
  I am Will Thomason, a program facilitator and creator working in the non-profit sector.

# social links
twitter_username: Will_Thomason # DO NOT include the @ character, or else the build will fail!
github_username:  Will-Thomason # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
